export const Colors = {
  light: {
    // Modern Copilot-inspired color scheme
    background: '#FFFFFF',
    foreground: '#1F2937',
    card: '#FFFFFF',
    cardBorder: '#E5E7EB',
    primary: '#1048c0ff',
    primaryForeground: '#FFFFFF',
    secondary: '#F3F4F6',
    secondaryForeground: '#374151',
    muted: '#F9FAFB',
    mutedForeground: '#6B7280',
    accent: '#EFF6FF',
    accentForeground: '#1D4ED8',
    border: '#E5E7EB',
    input: '#F9FAFB',
    ring: '#2563EB',
    success: '#059669',
    successForeground: '#FFFFFF',
    warning: '#D97706',
    warningForeground: '#FFFFFF',
    error: '#DC2626',
    errorForeground: '#FFFFFF',
    destructive: '#DC2626',
    destructiveForeground: '#FFFFFF',
    text: '#374151',
  },
  dark: {
    background: '#030213',
    foreground: '#ffffff',
    card: '#1a1a1a',
    cardForeground: '#ffffff',
    primary: '#ffffff',
    primaryForeground: '#030213',
    secondary: '#2a2a2a',
    secondaryForeground: '#ffffff',
    muted: '#2a2a2a',
    mutedForeground: '#a1a1aa',
    accent: '#2a2a2a',
    accentForeground: '#ffffff',
    destructive: '#dc2626',
    destructiveForeground: '#ffffff',
    border: '#2a2a2a',
    success: '#16a34a',
    warning: '#d97706',
    error: '#dc2626',
  }
};